modLoader="javafml"
loaderVersion="[47,)"

license="CC BY-NC-SA 3.0"
issueTrackerURL="https://github.com/J4gm/jagmkiwis/issues"

[[mods]]
	modId="jagmkiwis"
	version="1.20.1-1.2"
	displayName="Jagm's Kiwis"
	displayURL="https://github.com/J4gm/jagmkiwis"
	authors="Jagm"
	description="Adds kiwi birds!"
	
[[dependencies.jagmkiwis]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jagmkiwis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"